reject Kernel panic
send echo go=$((6*7))\n
expect go=42
send spimode net\n
expect eth0
send ip link set eth0 address 02:00:00:00:00:20 && ip addr add 10.0.0.20/24 dev eth0 && ip link set eth0 mtu 114 up && echo up=$((1+1))\n
expect up=2
send ip route add 10.0.0.0/8 via 10.0.0.1 && echo rt=$((2+1))\n
expect rt=3
send ping -c 3 10.0.0.10\n
expect 3 packets received
send ping -c 3 10.0.1.10\n
expect ttl=63
expect 3 packets received
